/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContaBloqueadaRouteImport } from './routes/conta-bloqueada'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AssinaturaPendenteRouteImport } from './routes/assinatura-pendente'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminExtrasRouteImport } from './routes/admin.extras'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedExcluirDadosRouteImport } from './routes/_authenticated/excluir-dados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated/agendar'
import { Route as ApiGoogleCalendarDisconnectRouteImport } from './routes/api/google-calendar/disconnect'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as AdminConfiguracoesZonaDePerigoRouteImport } from './routes/admin.configuracoes.zona-de-perigo'
import { Route as AdminConfiguracoesSegurancaRouteImport } from './routes/admin.configuracoes.seguranca'
import { Route as AdminConfiguracoesPagamentosRouteImport } from './routes/admin.configuracoes.pagamentos'
import { Route as AdminConfiguracoesNotificacoesRouteImport } from './routes/admin.configuracoes.notificacoes'
import { Route as AdminConfiguracoesIntegracoesRouteImport } from './routes/admin.configuracoes.integracoes'
import { Route as AdminConfiguracoesGeralRouteImport } from './routes/admin.configuracoes.geral'
import { Route as AdminConfiguracoesEstabelecimentoRouteImport } from './routes/admin.configuracoes.estabelecimento'
import { Route as AdminConfiguracoesAparenciaRouteImport } from './routes/admin.configuracoes.aparencia'
import { Route as AdminConfiguracoesAgendaRouteImport } from './routes/admin.configuracoes.agenda'
import { Route as AdminConfiguracoesAdministradorRouteImport } from './routes/admin.configuracoes.administrador'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaBloqueadaRoute = ContaBloqueadaRouteImport.update({
  id: '/conta-bloqueada',
  path: '/conta-bloqueada',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaPendenteRoute = AssinaturaPendenteRouteImport.update({
  id: '/assinatura-pendente',
  path: '/assinatura-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtrasRoute = AdminExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExcluirDadosRoute =
  AuthenticatedExcluirDadosRouteImport.update({
    id: '/excluir-dados',
    path: '/excluir-dados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiGoogleCalendarDisconnectRoute =
  ApiGoogleCalendarDisconnectRouteImport.update({
    id: '/api/google-calendar/disconnect',
    path: '/api/google-calendar/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesZonaDePerigoRoute =
  AdminConfiguracoesZonaDePerigoRouteImport.update({
    id: '/zona-de-perigo',
    path: '/zona-de-perigo',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesSegurancaRoute =
  AdminConfiguracoesSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesPagamentosRoute =
  AdminConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesNotificacoesRoute =
  AdminConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesIntegracoesRoute =
  AdminConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesGeralRoute = AdminConfiguracoesGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => AdminConfiguracoesRoute,
} as any)
const AdminConfiguracoesEstabelecimentoRoute =
  AdminConfiguracoesEstabelecimentoRouteImport.update({
    id: '/estabelecimento',
    path: '/estabelecimento',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesAparenciaRoute =
  AdminConfiguracoesAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesAgendaRoute =
  AdminConfiguracoesAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesAdministradorRoute =
  AdminConfiguracoesAdministradorRouteImport.update({
    id: '/administrador',
    path: '/administrador',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/assinatura-pendente': typeof AssinaturaPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/excluir-dados': typeof AuthenticatedExcluirDadosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/configuracoes/administrador': typeof AdminConfiguracoesAdministradorRoute
  '/admin/configuracoes/agenda': typeof AdminConfiguracoesAgendaRoute
  '/admin/configuracoes/aparencia': typeof AdminConfiguracoesAparenciaRoute
  '/admin/configuracoes/estabelecimento': typeof AdminConfiguracoesEstabelecimentoRoute
  '/admin/configuracoes/geral': typeof AdminConfiguracoesGeralRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/notificacoes': typeof AdminConfiguracoesNotificacoesRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/seguranca': typeof AdminConfiguracoesSegurancaRoute
  '/admin/configuracoes/zona-de-perigo': typeof AdminConfiguracoesZonaDePerigoRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/assinatura-pendente': typeof AssinaturaPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/excluir-dados': typeof AuthenticatedExcluirDadosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/health': typeof ApiHealthRoute
  '/admin': typeof AdminIndexRoute
  '/admin/configuracoes/administrador': typeof AdminConfiguracoesAdministradorRoute
  '/admin/configuracoes/agenda': typeof AdminConfiguracoesAgendaRoute
  '/admin/configuracoes/aparencia': typeof AdminConfiguracoesAparenciaRoute
  '/admin/configuracoes/estabelecimento': typeof AdminConfiguracoesEstabelecimentoRoute
  '/admin/configuracoes/geral': typeof AdminConfiguracoesGeralRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/notificacoes': typeof AdminConfiguracoesNotificacoesRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/seguranca': typeof AdminConfiguracoesSegurancaRoute
  '/admin/configuracoes/zona-de-perigo': typeof AdminConfiguracoesZonaDePerigoRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/assinatura-pendente': typeof AssinaturaPendenteRoute
  '/cadastro': typeof CadastroRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/excluir-dados': typeof AuthenticatedExcluirDadosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/extras': typeof AdminExtrasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/configuracoes/administrador': typeof AdminConfiguracoesAdministradorRoute
  '/admin/configuracoes/agenda': typeof AdminConfiguracoesAgendaRoute
  '/admin/configuracoes/aparencia': typeof AdminConfiguracoesAparenciaRoute
  '/admin/configuracoes/estabelecimento': typeof AdminConfiguracoesEstabelecimentoRoute
  '/admin/configuracoes/geral': typeof AdminConfiguracoesGeralRoute
  '/admin/configuracoes/integracoes': typeof AdminConfiguracoesIntegracoesRoute
  '/admin/configuracoes/notificacoes': typeof AdminConfiguracoesNotificacoesRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/seguranca': typeof AdminConfiguracoesSegurancaRoute
  '/admin/configuracoes/zona-de-perigo': typeof AdminConfiguracoesZonaDePerigoRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/aguardando-aprovacao'
    | '/assinatura-pendente'
    | '/cadastro'
    | '/conta-bloqueada'
    | '/forgot-password'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/agendar'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/excluir-dados'
    | '/historico'
    | '/perfil'
    | '/planos'
    | '/veiculos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/configuracoes'
    | '/admin/extras'
    | '/admin/financeiro'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/api/health'
    | '/admin/'
    | '/admin/configuracoes/administrador'
    | '/admin/configuracoes/agenda'
    | '/admin/configuracoes/aparencia'
    | '/admin/configuracoes/estabelecimento'
    | '/admin/configuracoes/geral'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/notificacoes'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/seguranca'
    | '/admin/configuracoes/zona-de-perigo'
    | '/api/auth/google'
    | '/api/google-calendar/disconnect'
    | '/api/auth/google/callback'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/aguardando-aprovacao'
    | '/assinatura-pendente'
    | '/cadastro'
    | '/conta-bloqueada'
    | '/forgot-password'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/agendar'
    | '/configuracoes'
    | '/conta'
    | '/dashboard'
    | '/excluir-dados'
    | '/historico'
    | '/perfil'
    | '/planos'
    | '/veiculos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/configuracoes'
    | '/admin/extras'
    | '/admin/financeiro'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/api/health'
    | '/admin'
    | '/admin/configuracoes/administrador'
    | '/admin/configuracoes/agenda'
    | '/admin/configuracoes/aparencia'
    | '/admin/configuracoes/estabelecimento'
    | '/admin/configuracoes/geral'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/notificacoes'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/seguranca'
    | '/admin/configuracoes/zona-de-perigo'
    | '/api/auth/google'
    | '/api/google-calendar/disconnect'
    | '/api/auth/google/callback'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/aguardando-aprovacao'
    | '/assinatura-pendente'
    | '/cadastro'
    | '/conta-bloqueada'
    | '/forgot-password'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/_authenticated/agendar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conta'
    | '/_authenticated/dashboard'
    | '/_authenticated/excluir-dados'
    | '/_authenticated/historico'
    | '/_authenticated/perfil'
    | '/_authenticated/planos'
    | '/_authenticated/veiculos'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/configuracoes'
    | '/admin/extras'
    | '/admin/financeiro'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/relatorios'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/api/health'
    | '/admin/'
    | '/admin/configuracoes/administrador'
    | '/admin/configuracoes/agenda'
    | '/admin/configuracoes/aparencia'
    | '/admin/configuracoes/estabelecimento'
    | '/admin/configuracoes/geral'
    | '/admin/configuracoes/integracoes'
    | '/admin/configuracoes/notificacoes'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/seguranca'
    | '/admin/configuracoes/zona-de-perigo'
    | '/api/auth/google'
    | '/api/google-calendar/disconnect'
    | '/api/auth/google/callback'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AssinaturaPendenteRoute: typeof AssinaturaPendenteRoute
  CadastroRoute: typeof CadastroRoute
  ContaBloqueadaRoute: typeof ContaBloqueadaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiGoogleCalendarDisconnectRoute: typeof ApiGoogleCalendarDisconnectRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-bloqueada': {
      id: '/conta-bloqueada'
      path: '/conta-bloqueada'
      fullPath: '/conta-bloqueada'
      preLoaderRoute: typeof ContaBloqueadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-pendente': {
      id: '/assinatura-pendente'
      path: '/assinatura-pendente'
      fullPath: '/assinatura-pendente'
      preLoaderRoute: typeof AssinaturaPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extras': {
      id: '/admin/extras'
      path: '/extras'
      fullPath: '/admin/extras'
      preLoaderRoute: typeof AdminExtrasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/excluir-dados': {
      id: '/_authenticated/excluir-dados'
      path: '/excluir-dados'
      fullPath: '/excluir-dados'
      preLoaderRoute: typeof AuthenticatedExcluirDadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/google-calendar/disconnect': {
      id: '/api/google-calendar/disconnect'
      path: '/api/google-calendar/disconnect'
      fullPath: '/api/google-calendar/disconnect'
      preLoaderRoute: typeof ApiGoogleCalendarDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/zona-de-perigo': {
      id: '/admin/configuracoes/zona-de-perigo'
      path: '/zona-de-perigo'
      fullPath: '/admin/configuracoes/zona-de-perigo'
      preLoaderRoute: typeof AdminConfiguracoesZonaDePerigoRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/seguranca': {
      id: '/admin/configuracoes/seguranca'
      path: '/seguranca'
      fullPath: '/admin/configuracoes/seguranca'
      preLoaderRoute: typeof AdminConfiguracoesSegurancaRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/pagamentos': {
      id: '/admin/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/configuracoes/pagamentos'
      preLoaderRoute: typeof AdminConfiguracoesPagamentosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/notificacoes': {
      id: '/admin/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/configuracoes/notificacoes'
      preLoaderRoute: typeof AdminConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/integracoes': {
      id: '/admin/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/admin/configuracoes/integracoes'
      preLoaderRoute: typeof AdminConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/geral': {
      id: '/admin/configuracoes/geral'
      path: '/geral'
      fullPath: '/admin/configuracoes/geral'
      preLoaderRoute: typeof AdminConfiguracoesGeralRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/estabelecimento': {
      id: '/admin/configuracoes/estabelecimento'
      path: '/estabelecimento'
      fullPath: '/admin/configuracoes/estabelecimento'
      preLoaderRoute: typeof AdminConfiguracoesEstabelecimentoRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/aparencia': {
      id: '/admin/configuracoes/aparencia'
      path: '/aparencia'
      fullPath: '/admin/configuracoes/aparencia'
      preLoaderRoute: typeof AdminConfiguracoesAparenciaRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/agenda': {
      id: '/admin/configuracoes/agenda'
      path: '/agenda'
      fullPath: '/admin/configuracoes/agenda'
      preLoaderRoute: typeof AdminConfiguracoesAgendaRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/administrador': {
      id: '/admin/configuracoes/administrador'
      path: '/administrador'
      fullPath: '/admin/configuracoes/administrador'
      preLoaderRoute: typeof AdminConfiguracoesAdministradorRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExcluirDadosRoute: typeof AuthenticatedExcluirDadosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExcluirDadosRoute: AuthenticatedExcluirDadosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminConfiguracoesRouteChildren {
  AdminConfiguracoesAdministradorRoute: typeof AdminConfiguracoesAdministradorRoute
  AdminConfiguracoesAgendaRoute: typeof AdminConfiguracoesAgendaRoute
  AdminConfiguracoesAparenciaRoute: typeof AdminConfiguracoesAparenciaRoute
  AdminConfiguracoesEstabelecimentoRoute: typeof AdminConfiguracoesEstabelecimentoRoute
  AdminConfiguracoesGeralRoute: typeof AdminConfiguracoesGeralRoute
  AdminConfiguracoesIntegracoesRoute: typeof AdminConfiguracoesIntegracoesRoute
  AdminConfiguracoesNotificacoesRoute: typeof AdminConfiguracoesNotificacoesRoute
  AdminConfiguracoesPagamentosRoute: typeof AdminConfiguracoesPagamentosRoute
  AdminConfiguracoesSegurancaRoute: typeof AdminConfiguracoesSegurancaRoute
  AdminConfiguracoesZonaDePerigoRoute: typeof AdminConfiguracoesZonaDePerigoRoute
}

const AdminConfiguracoesRouteChildren: AdminConfiguracoesRouteChildren = {
  AdminConfiguracoesAdministradorRoute: AdminConfiguracoesAdministradorRoute,
  AdminConfiguracoesAgendaRoute: AdminConfiguracoesAgendaRoute,
  AdminConfiguracoesAparenciaRoute: AdminConfiguracoesAparenciaRoute,
  AdminConfiguracoesEstabelecimentoRoute:
    AdminConfiguracoesEstabelecimentoRoute,
  AdminConfiguracoesGeralRoute: AdminConfiguracoesGeralRoute,
  AdminConfiguracoesIntegracoesRoute: AdminConfiguracoesIntegracoesRoute,
  AdminConfiguracoesNotificacoesRoute: AdminConfiguracoesNotificacoesRoute,
  AdminConfiguracoesPagamentosRoute: AdminConfiguracoesPagamentosRoute,
  AdminConfiguracoesSegurancaRoute: AdminConfiguracoesSegurancaRoute,
  AdminConfiguracoesZonaDePerigoRoute: AdminConfiguracoesZonaDePerigoRoute,
}

const AdminConfiguracoesRouteWithChildren =
  AdminConfiguracoesRoute._addFileChildren(AdminConfiguracoesRouteChildren)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRouteWithChildren
  AdminExtrasRoute: typeof AdminExtrasRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRouteWithChildren,
  AdminExtrasRoute: AdminExtrasRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AssinaturaPendenteRoute: AssinaturaPendenteRoute,
  CadastroRoute: CadastroRoute,
  ContaBloqueadaRoute: ContaBloqueadaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiGoogleCalendarDisconnectRoute: ApiGoogleCalendarDisconnectRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
